### ISSUE TITLE
pb_bnet_avatar

### ISSUE THREAD

**Issue by Xolgrunek** [PayBas/PBWoW3ext#17]
pb_bnet_avatar uses the old static render domain.

announcement: https://us.battle.net/forums/en/wow/topic/20752046076

old: https://render-api-us.worldofwarcraft.com/static-render/us/zuljin/184/182473912-avatar.jpg

new: https://render-us.worldofwarcraft.com/character/zuljin/184/182473912-avatar.jpg

currently using 3.05

edit: this issue only appears to affect characters made or transferred after the change was put in place.

**Comment by Galixte** [comment]
Hi @Elfmagi,

the new repository is here: https://github.com/bbDKP/PBWoW3ext.

**Comment by avandenberghe** [comment]
hi, this was implemented in the latest release
https://github.com/bbDKP/PBWoW3ext/releases
