### ISSUE TITLE
Case sensitivity of fields in PostgreSQL

### ISSUE THREAD

**Issue by MasterMind2k** [PayBas/PBWoW3ext#4]
Hi.

I've managed to get passed through the #1, by manually fixing queries. Another problem arose, with avatar cache. You are referencing the field with avatarURL, in postgresql (perhaps it is my fault)  was named avatarurl (all lowercase). Changing avatarURL to avatarurl on lines 491 and 501 in core/pbwow.php fixed the problem.

**Comment by PayBas** [comment]
Fixed in https://github.com/PayBas/PBWoW3ext/commit/68ca64fb6fab12add06243e9684ec7e3a338d8e5
