### ISSUE TITLE
Wrong URL for url characters with names containing special chars

### ISSUE THREAD

**Issue by troisplus** [PayBas/PBWoW3ext#5]
This problem occured on member profile. 

For example :
Player => Lanfÿ
Offical URL: http://eu.battle.net/wow/fr/character/kirin-tor/Lanf%C3%BF
Profile URL:http://eu.battle.net/wow/character/kirin-tor/lanf (with ÿ/ out of the tag)

my website : http://high-spirits.fr/

**Comment by PayBas** [comment]
This should be fixed in phpBB 3.1.3

https://tracker.phpbb.com/browse/PHPBB3-12926

**Comment by troisplus** [comment]
It's ok with the update ^^

thx
