### ISSUE TITLE
Avatar location defaults to HTTP

### ISSUE THREAD

**Issue by sadris** [PayBas/PBWoW3ext#6]
PBWoW sets the avatarURL to http instead of whatever the site is hosted behind. This makes web-browsers complain about loading HTTP content whilst connected to an HTTPS site.

Line is:
 $avatarURL = "http://" . $bnet_loc . "/static-render/" . $loc . "/" . $avatar;

in core.php.

For my use, I just hard-coded it to https

**Comment by PayBas** [comment]
Fixed in https://github.com/PayBas/PBWoW3ext/commit/ad879f1532de285fc1a2b575ab2690404c65d98f
